### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by jandegier** [aig-upf/temporal-planning#2]
For the Fast Downward compilation to work, I needed to include <cmath> in the following two files:
- fd_copy/src/search/merge_and_shrink/merge_and_shrink_heuristic.cc
- fd_copy/src/search/operator_counting/operator_counting_heuristic.cc

**Comment by ertsiger** [comment]
Thanks @jandegier. I could reproduce the error in newer Ubuntu versions. I have just applied the changes to the repository (8c0079c8f08e098a4cba02cd12cb2c5ea9642b82).
