### ISSUE TITLE
Cannot use the make command to compile the validator tool

### ISSUE THREAD

**Issue by axelvan22** [aig-upf/temporal-planning#3]
Hello,

I'm trying to use this planner for a work but I can't use it because of the lack of a plan validator tool.

I've tried to compile the code of https://github.com/KCL-Planning/VAL with the  make command but the VAL directory doesn't have any makefile. I've also tried to build it with the script but it has not solved my problem...

Did anyone else encountered this problem? If so, how did you solve it?

**Comment by ertsiger** [comment]
Hi,

it seems the compilation process has slightly changed. Try the following:
```
cmake CMakeLists.txt 
make
```
The first command should produce the Makefile you need. The `bin` folder will contain the `Validate` binary, which is the one that should be used now, if I'm not wrong.

I haven't personally tried the last version of VAL, but hopefully it will still work the same way. If you have any other problems, let us know.

**Comment by axelvan22** [comment]
Thank you, it worked!

But the script still cannot find the validator, isn't it because the directories have changed? I have this error message :
`Command '['/**/miniconda3/bin/python', '/***/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/translate.py', 'dom.pddl', 'ins.pddl']' returned non-zero exit status 1.
Error: Could not find the validator (current path: /***/planner_temporel/temporal-planning/../VAL/validate)`

I will be looking for earlier versions of VAL to see if it's the problem.

**Comment by ertsiger** [comment]
Yes, I didn't think about this, sorry. Try changing the directory in this line: https://github.com/aig-upf/temporal-planning/blob/master/bin/plan.py#L129 from "../VAL/validate" to "../VAL/bin/Validate". The code should definitely work with the VAL version from 2018 if you don't manage to make our code work with the latest version.

**Comment by axelvan22** [comment]
I'm closing this issue, thank you for your quick response!
