### ISSUE TITLE
No plan found for example 1 and 2

### ISSUE THREAD

**Issue by axelvan22** [aig-upf/temporal-planning#4]
Hi,

I managed to get the code working with the newest version, as well as with the one I'm using (the code is available here https://github.com/KCL-Planning/VAL/tree/a5565396007eee73ac36527fbf904142b3077c74 ).

Then I wanted to test the planner with the examples found in the README file but no plan could be found. I tried to force the iterations with the option `--iterated` but it did nothing.

Here are the errors I get when I try running `python bin/plan.py she domains/AllenAlgebra/domain/domain.pddl domains/AllenAlgebra/problems/pfile10.pddl --generator domains/AllenAlgebra/problems/generator --iterated ` : 

`Parsing...
Traceback (most recent call last):
  File "/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/translate.py", line 683, in <module>
    main()
  File "/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/translate.py", line 661, in main
    domain_filename=options.domain, task_filename=options.task)
  File "/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/pddl_parser/pddl_file.py", line 34, in open
    domain_pddl = parse_pddl_file("domain", domain_filename)
  File "/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/pddl_parser/pddl_file.py", line 22, in parse_pddl_file
    encoding='ISO-8859-1'))
  File "/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/pddl_parser/lisp_parser.py", line 12, in parse_nested_list
    next_token = next(tokens)
StopIteration
Command '['/*/miniconda2/envs/py2/bin/python', '/**/planner_temporel/temporal-planning/fd_copy/builds/release64/bin/translate/translate.py', 'dom.pddl', 'ins.pddl']' returned non-zero exit status 1
Error: No solution to be converted into temporal has been found
Error: No plan to validate was found`

The python version used for this is 2.7.18 .

I got the same problem with the newest version of VAL .

**Comment by ertsiger** [comment]
Hi,

there was a line missing in the `SConstruct` file to compile the generator for the AllenAlgebra domain. I have just added it, so if you run `git pull` you should have the updated version. Then you just have to run `build.sh` again (or `scons`) and it will be compiled. Then, you will be able to run that example :)

Hope this helps!

**Comment by ertsiger** [comment]
Hi again,

I have added `VAL` as a submodule. So if you pull the repository and run `build.sh`, you should have everything you need in one place :) Then you can run the example commands and everything should work.

**Comment by axelvan22** [comment]
H,

Thank you for your help, it works now!

I had another problem with the `build.sh` because of the use of Scons with later versions of python than the 2.7 . For those that meet the same issue, here's what helped me go through it : https://github.com/SCons/scons/issues/3402#issuecomment-507899313 .
