### ISSUE TITLE
Fast-Downward compilation error

### ISSUE THREAD

**Issue by hypothe** [aig-upf/temporal-planning#5]
Might be some really basic thing I'm missing here, but "python fd_copy/build.py release64" fails at "Building CXX object search/CMakeFiles/downward.dir/potentials/util.cc.o" due to 

`<path>/temporal-planning/fd_copy/src/search/ext/tree_util.hh:78:18: error: implicitly-declared ‘tree<options::ParseNode>::sibling_iterator& tree<options::ParseNode>::sibling_iterator::operator=(const tree<options::ParseNode>::sibling_iterator&)’ is deprecated [-Werror=deprecated-copy]
    78 |   for (iChildren = t.begin(iRoot), siblingNum = 0; iChildren != t.end(iRoot); ++iChildren, ++siblingNum) {
In file included from <path>/temporal-planning/fd_copy/src/search/potentials/../options/parse_tree.h:7,
                 from <path>/temporal-planning/fd_copy/src/search/potentials/../options/errors.h:4,
                 from <path>/temporal-planning/fd_copy/src/search/potentials/../option_parser.h:6,
                from <path>/temporal-planning/fd_copy/src/search/potentials/util.cc:7:
<path>/temporal-planning/fd_copy/src/search/ext/tree.hh:2519:1: note: because ‘tree<options::ParseNode>::sibling_iterator’ has user-provided ‘tree<T, tree_node_allocator>::sibling_iterator::sibling_iterator(const tree<T, tree_node_allocator>::sibling_iterator&) [with T = options::ParseNode; tree_node_allocator = std::allocator<tree_node_<options::ParseNode> >]’
  2519 | tree<T, tree_node_allocator>::sibling_iterator::sibling_iterator(const sibling_iterator& other)
`
on an Ubuntu 20.04 VM.

**Comment by ertsiger** [comment]
Hi,

it seems it is a problem that has appeared with the latest Ubuntu versions. I have just updated one file according to the last Fast Downward version that solves the problem. Please try again and let us know :)

**Comment by hypothe** [comment]
Hi, thanks for the quick reply!
Everything compiles flawlessly now, no problems testing it on the provided domains, thanks for the fix ^^
