### ISSUE TITLE
Support for `not` keyword on problem file

### ISSUE THREAD

**Issue by tallpress** [aig-upf/temporal-planning#7]
I am trying to define a problem file that has the following structure
```lisp
(define (problem em_problem)
    (:domain em_domain)

    (:objects
        plate1 - plate
    )

    (:init
        (not (capped plate1))
    )

    (:goal (and
        (capped plate1)
        )
    )
    (:metric minimize (total-time))
)
```
Having looked over the parse code a bit, the parser is seemingly not able to parse the `not` keyword when it is part of the `init` or `goal`.

I found this as well in https://github.com/aig-upf/temporal-planning/blob/master/fd_copy/src/translate/translate.py
```
    assert len(goal_dict_list) == 1, "Negative goal not supported"
    ## we could substitute the negative goal literal in
    ## normalize.substitute_complicated_goal, using an axiom. We currently
    ## don't do this, because we don't run into this assertion, if the
    ## negative goal is part of finite domain variable with only two
    ## values, which is most of the time the case, and hence refrain from
    ## introducing axioms (that are not supported by all heuristics)
```

I'm not sure if this is for a specific reason or it's missing and can theoretically be added?

**Comment by tallpress** [comment]
I found this... in https://github.com/aig-upf/temporal-planning/blob/master/fd_copy/src/translate/translate.py
```
    assert len(goal_dict_list) == 1, "Negative goal not supported"
    ## we could substitute the negative goal literal in
    ## normalize.substitute_complicated_goal, using an axiom. We currently
    ## don't do this, because we don't run into this assertion, if the
    ## negative goal is part of finite domain variable with only two
    ## values, which is most of the time the case, and hence refrain from
    ## introducing axioms (that are not supported by all heuristics)
```

**Comment by ertsiger** [comment]
As far as I remember, the initial state is specified only in terms of positive atoms (everything else is assumed to be false). Thus, if you want `(capped plate1)` to be false, you just do not have to mention it in `:init` :)

**Comment by wisdompoet** [comment]
There might be a problem with our parser if the initial state is empty,
can't remember for sure.

An alternative way to model negative initial and goal conditions is to
introduce duplicate fluents that are true exactly when the original fluents
are false. In your case this would introduce a separate predicate
"not-capped" or similar, and actions who delete "capped" also add
"not-capped", and vice versa. Now you can represent that "capped" is false
using a positive initial or goal condition "not-capped".

Missatge de Daniel Furelos Blanco ***@***.***> del dia dc.,
16 de nov. 2022 a les 12:17:

**Comment by tallpress** [comment]
nice, this seemed to do nice the job, thanks for the help @ertsiger @wisdompoet
